#!/usr/bin/env php
<?php

if(isset($GLOBALS['_composer_autoload_path'])) {
    require $GLOBALS['_composer_autoload_path'];
} else {
    require __DIR__.'/vendor/autoload.php';
}

use LTT\Console\InitAppCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new InitAppCommand(true));

try {
    $application->run();
} catch (Exception $e) {
    print_r($e->getMessage());
}