#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use LTT\Console\InitAppCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new InitAppCommand(true));

try {
    $application->run();
} catch (Exception $e) {
    print_r($e->getMessage());
}