#!/usr/bin/env php
<?php

if(str_contains(__DIR__,'vendor/bin')) {
    require __DIR__.'/../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use LTT\Console\InitAppCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new InitAppCommand(true));

try {
    $application->run();
} catch (Exception $e) {
    print_r($e->getMessage());
}